import { execFileSync } from "node:child_process";
import { mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { beforeAll, describe, expect, it, vi } from "vitest";

import type { ExtractedAudioSummary } from "@/types/processing-job";

import { DevelopmentArtifactStorage } from "@/server/artifacts/development-artifact-storage";
import { InMemoryProcessingJobRepository } from "@/server/processing/development-job-repository";
import {
  FfmpegMediaProcessor,
  resolveBinaryPath,
} from "@/server/processing/ffmpeg-media-processor";
import { UploadedProcessingMediaSource } from "@/server/processing/processing-media-source";
import { ProcessingService } from "@/server/processing/processing-service";
import { LocalTemporaryFileManager } from "@/server/processing/temporary-file-manager";

/**
 * Integration checks that actually execute FFmpeg and FFprobe.
 *
 * Fixtures are generated by FFmpeg itself (a few seconds of test pattern plus
 * a sine tone), so nothing large is committed and nothing depends on a
 * machine-specific path. When the binaries are unavailable these tests are
 * skipped — a skip is reported as a skip, never as a pass.
 *
 * Job-level cancellation (state transition plus temp-directory cleanup) is
 * covered in processing-service.test.ts with a controllable processor; here the
 * concern is that a real FFmpeg child process is actually terminated.
 */

const ffmpegPath = resolveBinaryPath("ffmpeg");
const ffprobePath = resolveBinaryPath("ffprobe");

function canRun(binaryPath: string): boolean {
  try {
    execFileSync(binaryPath, ["-version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

const ffmpegAvailable = canRun(ffmpegPath);
const ffprobeAvailable = canRun(ffprobePath);

if (!ffmpegAvailable || !ffprobeAvailable) {
  console.warn(
    `[aidub tests] Skipping FFmpeg integration tests: ffmpeg=${ffmpegAvailable}, ffprobe=${ffprobeAvailable}`,
  );
}

/**
 * Counts live processes whose command line mentions a path — used to prove a
 * cancelled FFmpeg run leaves nothing orphaned. Linux-only, which is what this
 * environment provides.
 */
async function ffmpegProcessCount(marker: string): Promise<number> {
  const { readdir, readFile: read } = await import("node:fs/promises");
  let count = 0;

  for (const entry of await readdir("/proc")) {
    if (!/^\d+$/.test(entry)) continue;

    try {
      const cmdline = (await read(`/proc/${entry}/cmdline`)).toString();
      if (cmdline.includes(marker)) count += 1;
    } catch {
      // The process disappeared between listing and reading.
    }
  }

  return count;
}

async function exists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

describe.skipIf(!ffmpegAvailable || !ffprobeAvailable)(
  "FFmpeg integration",
  () => {
    let fixtures: string;
    let withAudio: string;
    let withoutAudio: string;
    let notMedia: string;
    let longAudio: string;

    beforeAll(async () => {
      fixtures = await mkdtemp(path.join(tmpdir(), "aidub-fixtures-"));
      withAudio = path.join(fixtures, "with-audio.mp4");
      withoutAudio = path.join(fixtures, "no-audio.mp4");
      notMedia = path.join(fixtures, "not-media.mp4");

      // 2s of 320x240 @ 15fps test pattern with a 440 Hz sine track.
      execFileSync(
        ffmpegPath,
        [
          "-hide_banner",
          "-loglevel",
          "error",
          "-y",
          "-f",
          "lavfi",
          "-i",
          "testsrc=size=320x240:rate=15:duration=2",
          "-f",
          "lavfi",
          "-i",
          "sine=frequency=440:duration=2",
          "-c:v",
          "libx264",
          "-pix_fmt",
          "yuv420p",
          "-c:a",
          "aac",
          "-shortest",
          withAudio,
        ],
        { stdio: "ignore" },
      );

      execFileSync(
        ffmpegPath,
        [
          "-hide_banner",
          "-loglevel",
          "error",
          "-y",
          "-f",
          "lavfi",
          "-i",
          "testsrc=size=160x120:rate=10:duration=1",
          "-c:v",
          "libx264",
          "-pix_fmt",
          "yuv420p",
          withoutAudio,
        ],
        { stdio: "ignore" },
      );

      // 20 s of audio: with `-re` this takes 20 s to convert, so a running
      // FFmpeg process can be caught and cancelled.
      longAudio = path.join(fixtures, "long-audio.m4a");
      execFileSync(
        ffmpegPath,
        [
          "-hide_banner",
          "-loglevel",
          "error",
          "-y",
          "-f",
          "lavfi",
          "-i",
          "sine=frequency=440:duration=20",
          "-c:a",
          "aac",
          longAudio,
        ],
        { stdio: "ignore" },
      );

      await writeFile(notMedia, "this is not a video");
    }, 60_000);

    function createService(root: string) {
      const artifacts = new DevelopmentArtifactStorage(
        path.join(root, "artifacts"),
      );
      const service = new ProcessingService({
        repository: new InMemoryProcessingJobRepository(),
        processor: new FfmpegMediaProcessor(),
        temporaryFiles: new LocalTemporaryFileManager(root),
        artifacts,
        mediaSource: new UploadedProcessingMediaSource(),
        logger: () => {},
      });

      return { service, artifacts };
    }

    it("reports both binaries as available", async () => {
      const capabilities = await new FfmpegMediaProcessor().getCapabilities();

      expect(capabilities.ffmpegAvailable).toBe(true);
      expect(capabilities.ffprobeAvailable).toBe(true);
      expect(capabilities.ffmpegVersion).toMatch(/ffmpeg version/i);
      expect(capabilities.ffprobeVersion).toMatch(/ffprobe version/i);
    });

    it("probes a real file through FFprobe", async () => {
      const metadata = await new FfmpegMediaProcessor().probe({
        inputPath: withAudio,
      });

      expect(metadata.durationSeconds).toBeGreaterThan(1.5);
      expect(metadata.durationSeconds).toBeLessThan(3);
      expect(metadata.container).toContain("mp4");
      expect(metadata.video).toMatchObject({
        codec: "h264",
        width: 320,
        height: 240,
        frameRate: 15,
      });
      expect(metadata.audio).toMatchObject({ codec: "aac" });
      expect(metadata.audio?.sampleRate).toBeGreaterThan(0);
    });

    it("detects that a file has no audio stream", async () => {
      const metadata = await new FfmpegMediaProcessor().probe({
        inputPath: withoutAudio,
      });

      expect(metadata.video).not.toBeNull();
      expect(metadata.audio).toBeNull();
    });

    it("fails cleanly on a file that is not media", async () => {
      await expect(
        new FfmpegMediaProcessor().probe({ inputPath: notMedia }),
      ).rejects.toMatchObject({ code: "PROBE_FAILED" });
    });

    it("fails cleanly when the input file does not exist", async () => {
      await expect(
        new FfmpegMediaProcessor().probe({
          inputPath: path.join(fixtures, "missing.mp4"),
        }),
      ).rejects.toMatchObject({ code: "PROBE_FAILED" });
    });

    it("runs a probe job end to end and cleans up", async () => {
      const root = await mkdtemp(path.join(tmpdir(), "aidub-probe-job-"));
      const { service } = createService(root);
      const bytes = new Uint8Array(await readFile(withAudio));

      const created = await service.createJob({
        projectId: "project-1",
        sourceMediaId: "media-1",
        type: "probe_media",
        uploadedSource: { bytes, filename: "with-audio.mp4" },
      });
      const finished = await service.runJob(created.id, {
        bytes,
        filename: "with-audio.mp4",
      });

      expect(finished.status).toBe("completed");
      expect(finished.progress).toBe(100);
      expect(finished.result).toMatchObject({ kind: "probe_media" });
      expect(
        (finished.result as { metadata: { video: { codec: string } } }).metadata
          .video.codec,
      ).toBe("h264");
      await expect(exists(path.join(root, "jobs", created.id))).resolves.toBe(
        false,
      );
    }, 60_000);

    it("extracts canonical mono 16 kHz PCM audio end to end", async () => {
      const root = await mkdtemp(path.join(tmpdir(), "aidub-extract-job-"));
      const { service } = createService(root);
      const bytes = new Uint8Array(await readFile(withAudio));

      const created = await service.createJob({
        projectId: "project-1",
        sourceMediaId: "media-1",
        type: "extract_audio",
        uploadedSource: { bytes, filename: "with-audio.mp4" },
      });
      const finished = await service.runJob(created.id, {
        bytes,
        filename: "with-audio.mp4",
      });

      expect(finished.status).toBe("completed");

      const artifact = (finished.result as { artifact: ExtractedAudioSummary })
        .artifact;

      expect(artifact).toMatchObject({
        filename: "extracted-audio.wav",
        mimeType: "audio/wav",
        sampleRate: 16000,
        channels: 1,
      });
      expect(artifact.sizeBytes).toBeGreaterThan(1000);
      expect(artifact.durationSeconds).toBeGreaterThan(1.5);

      // The stored artifact is a real, probeable WAV file.
      const stored = await service.getArtifact(artifact.id, "project-1");
      expect(stored?.bytes.byteLength).toBe(artifact.sizeBytes);

      const wavPath = path.join(root, "check.wav");
      await writeFile(wavPath, stored!.bytes);

      const wavProbe = await new FfmpegMediaProcessor().probe({
        inputPath: wavPath,
      });
      expect(wavProbe.audio).toMatchObject({
        codec: "pcm_s16le",
        sampleRate: 16000,
        channels: 1,
      });

      // The job's temp directory is gone, the artifact survived it.
      await expect(exists(path.join(root, "jobs", created.id))).resolves.toBe(
        false,
      );
    }, 60_000);

    it("fails an extraction when the source has no audio track", async () => {
      const root = await mkdtemp(path.join(tmpdir(), "aidub-no-audio-job-"));
      const { service } = createService(root);
      const bytes = new Uint8Array(await readFile(withoutAudio));

      const created = await service.createJob({
        projectId: "project-1",
        sourceMediaId: "media-2",
        type: "extract_audio",
        uploadedSource: { bytes, filename: "no-audio.mp4" },
      });
      const finished = await service.runJob(created.id, {
        bytes,
        filename: "no-audio.mp4",
      });

      expect(finished).toMatchObject({
        status: "failed",
        error: {
          code: "NO_AUDIO_STREAM",
          message: "No audio track was found in this source video.",
        },
      });
      await expect(exists(path.join(root, "jobs", created.id))).resolves.toBe(
        false,
      );
    }, 60_000);

    it("fails a job whose source is not media, and cleans up", async () => {
      const root = await mkdtemp(path.join(tmpdir(), "aidub-bad-source-"));
      const { service } = createService(root);
      const bytes = new Uint8Array(await readFile(notMedia));

      const created = await service.createJob({
        projectId: "project-1",
        sourceMediaId: "media-3",
        type: "probe_media",
        uploadedSource: { bytes, filename: "not-media.mp4" },
      });
      const finished = await service.runJob(created.id, {
        bytes,
        filename: "not-media.mp4",
      });

      expect(finished.status).toBe("failed");
      expect(finished.error?.code).toBe("PROBE_FAILED");
      // The message stays short and user-safe.
      expect(finished.error?.message.length).toBeLessThan(120);
      await expect(exists(path.join(root, "jobs", created.id))).resolves.toBe(
        false,
      );
    }, 60_000);

    it("terminates a real FFmpeg process on cancellation and cleans up", async () => {
      const root = await mkdtemp(path.join(tmpdir(), "aidub-cancel-"));
      const outputPath = path.join(root, "cancelled.wav");
      const processor = new FfmpegMediaProcessor();
      const controller = new AbortController();

      // `-re` makes FFmpeg read in real time, so a 20 s source takes 20 s to
      // convert — long enough to cancel a genuinely running process.
      const conversion = processor.convert(
        {
          inputPath: longAudio,
          outputPath,
          inputArgs: ["-re"],
          audio: { codec: "pcm_s16le", sampleRate: 16000, channels: 1 },
        },
        { signal: controller.signal },
      );

      await vi.waitFor(
        async () => {
          expect(await ffmpegProcessCount(longAudio)).toBeGreaterThan(0);
        },
        { timeout: 10_000 },
      );

      controller.abort();

      await expect(conversion).rejects.toMatchObject({ code: "CANCELLED" });

      // No orphaned child process is left behind.
      await vi.waitFor(
        async () => {
          expect(await ffmpegProcessCount(longAudio)).toBe(0);
        },
        { timeout: 10_000 },
      );
    }, 60_000);

  },
);
