import { mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { ProcessingError } from "@/server/processing/processing-errors";

/**
 * Job-scoped scratch space.
 *
 *   <os temp>/aidub/jobs/<jobId>/
 *     source.<ext>
 *     extracted-audio.wav
 *
 * Nothing here is project storage: every directory is removed when its job
 * finishes, fails or is cancelled. Filenames are generated by the backend —
 * user-supplied names never become paths.
 */

export const TEMP_ROOT_DIRECTORY_NAME = "aidub";
export const TEMP_JOBS_DIRECTORY_NAME = "jobs";

export interface TemporaryFileManager {
  createJobDirectory(jobId: string): Promise<string>;
  /** Absolute path inside the job directory for a backend-chosen filename. */
  createPath(jobId: string, filename: string): Promise<string>;
  cleanupJob(jobId: string): Promise<void>;
}

/** Rejects anything that could escape the job directory. */
const SAFE_SEGMENT = /^[A-Za-z0-9._-]+$/;

function assertSafeSegment(value: string, label: string): void {
  if (!SAFE_SEGMENT.test(value) || value === "." || value === "..") {
    throw new ProcessingError(
      "TEMP_STORAGE_ERROR",
      "Could not prepare temporary processing storage.",
      { details: `unsafe ${label}` },
    );
  }
}

export class LocalTemporaryFileManager implements TemporaryFileManager {
  constructor(private readonly rootDirectory: string = defaultTempRoot()) {}

  jobDirectory(jobId: string): string {
    assertSafeSegment(jobId, "job id");
    return path.join(this.rootDirectory, TEMP_JOBS_DIRECTORY_NAME, jobId);
  }

  async createJobDirectory(jobId: string): Promise<string> {
    const directory = this.jobDirectory(jobId);

    try {
      await mkdir(directory, { recursive: true });
    } catch (cause) {
      throw new ProcessingError(
        "TEMP_STORAGE_ERROR",
        "Could not prepare temporary processing storage.",
        { cause },
      );
    }

    return directory;
  }

  async createPath(jobId: string, filename: string): Promise<string> {
    assertSafeSegment(filename, "filename");
    const directory = await this.createJobDirectory(jobId);

    return path.join(directory, filename);
  }

  async cleanupJob(jobId: string): Promise<void> {
    await rm(this.jobDirectory(jobId), { recursive: true, force: true });
  }
}

export function defaultTempRoot(): string {
  return path.join(tmpdir(), TEMP_ROOT_DIRECTORY_NAME);
}
